#!/bin/bash
. "$(dirname $0)/settings.sh" || die "Unable to load settings.sh"

usage=$(
cat << EOF
Usage: $0 [PROJ_NAME]
EOF
)

if [ $# == 0 ] ; then
	echo "$usage"
else
	if [ -e "$1" ] ; then
		$RPKG_SCRIPT "$1" "$APP_ARC_DIR"
	else
		echo "$1 does not exist"
	fi
fi
