#!/bin/bash
. "$(dirname $0)/settings.sh" || die "Unable to load settings.sh"

usage=$(
cat << EOF
Usage: $0 [-sac]
-s SRC
-a APK
-c ARC
EOF
)

while getopts "sac" OPTION; do
	case "$OPTION" in 
		s) echo "Projects"
		   ls -1 $APP_SRC_DIR ;;
		a) echo "APK files"
		   ls -1 $APP_APK_DIR ;;
		c) echo "ARC repackages"
		   ls -1 $APP_ARC_DIR ;;
		*) echo "unrecognized option"
		   echo "$usage";;
	esac
done
